name: 'play-app'

services:
  postgres:
    container_name: postgres
    image: postgres:14.15-alpine3.21
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:8.0-M03-alpine3.21
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: