name: Scala Play Application CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt test