name: Scala Play Application CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SBT
        uses: sbt/setup-sbt@v1

#      - name: Check ScalaFix Formatting
#        run: sbt "scalafixAll --check" || (echo "Scalafix check failed!" && exit 1)

      - name: Check Scalafmt Formatting
        run: sbt scalafmtCheckAll

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run CI environment
        run: |
          cd ./docker
          cp .env.template .env
          ./pull.sh
          ./env.sh

      - name: Run tests
        run: sbt clean Ci/test coverageReport

      - name: Install SonarCloud Scan
        working-directory: .github/workflows
        run: ./install-sonar.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Run SonarCloud Scan
        id: sonar
        run: sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
