name: Scala Play Application CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install SBT
        uses: sbt/setup-sbt@v1

      - name: Check Formatting
        run: sbt "scalafixAll --check" || (echo "Scalafix check failed!" && exit 1)

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run CI environment
        run: |
          cd ./docker
          cp .env.template .env
          ./pull.sh
          ./env.sh

      - name: Run tests
        run: |
          sbt clean Ci/test coverageReport
          ls -lah target/scala-*/scoverage-report/


      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=${{ github.workspace }}
