name: Scala Play Application CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install SBT
        uses: sbt/setup-sbt@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run CI environment
        run: |
          cd ./docker
          ./env.sh

      - name: Run tests
        run: sbt test